build:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    untracked: true

deploy:
  dependencies:
    - build
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  only:
    - main
  before_script:
    - apk add --update zip
    - echo "The service-principal is '$AZURE_APP_ID'"
  script:
    # - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT
    - echo "az storage blob upload-batch -s ./build/ --account-name $STORAGE_ACCOUNT_NAME -d '$DESTINATION' --overwrite --sas-token '$SAS_TOKEN'"
    - az storage blob upload-batch -s ./build/ --account-name $STORAGE_ACCOUNT_NAME -d '"$DESTINATION"' --overwrite --sas-token '"$SAS_TOKEN"'

include:
  # https://docs.gitlab.com/ee/user/application_security/dependency_scanning/
  - template: Security/Dependency-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug
  DS_MAX_DEPTH: 3
