#build:
#  image: node:latest
#  stage: build
#  before_script:
#    - npm install
#  script:
#    - npm run build
#  artifacts:
#    untracked: true

#deploy:
#  dependencies:
#    - build
#  image: mcr.microsoft.com/azure-cli
#  stage: deploy
#  only:
#    - main
#  before_script:
#    - apk add --update zip
#    - echo "The service-principal is '$AZURE_APP_ID'"
#  script:
#    # - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT
#    - echo "az storage blob upload-batch -s ./build/ --account-name $STORAGE_ACCOUNT_NAME -d '$DESTINATION' --overwrite --sas-token '$SAS_TOKEN'"
#    - az storage blob upload-batch -s ./build/ --account-name $STORAGE_ACCOUNT_NAME -d "$DESTINATION" --overwrite --sas-token "$SAS_TOKEN"

# The Docker image that will be used to build your app
image: node:lts

before_script:
  # Functions that should be executed before the build script is run
  - npm install

pages:
  script:
    # Specify the steps involved to build your app here
    - npm run build
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public

  only:
    # Trigger a new build and deploy only when there is a push to the
    # below branch(es)
    - main
    - pages

include:
  # https://docs.gitlab.com/ee/user/application_security/dependency_scanning/
  - template: Security/Dependency-Scanning.gitlab-ci.yml
variables:
  SECURE_LOG_LEVEL: debug
  DS_MAX_DEPTH: 3
