name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          PUBLIC_CMS_URL: ${{ vars.PUBLIC_CMS_URL }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          folder: public
